#!/usr/bin/env node
/**
 * Renders scripts/og/card.html into the trycommons.app share card and bakes it
 * into packages/backend/convex/ogImage.ts, which the /og.jpg route serves.
 *
 *   node scripts/og/render.mjs
 *
 * Needs Google Chrome (headless) and macOS `sips`. Renders at 2x and
 * downsamples for clean edges, then encodes as a JPEG. Rerun after a
 * redesign; the page links the card at /og.jpg, so nothing else changes.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const card = path.join(here, "card.html");
const out = path.join(root, "packages/backend/convex/ogImage.ts");
const chrome = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";

const work = mkdtempSync(path.join(tmpdir(), "commons-og-"));
const png = path.join(work, "card.png");
const jpg = path.join(work, "card.jpg");

execFileSync(chrome, [
  "--headless=new",
  "--disable-gpu",
  "--hide-scrollbars",
  "--force-device-scale-factor=2",
  "--window-size=1200,630",
  "--virtual-time-budget=12000",
  `--screenshot=${png}`,
  `file://${card}`,
], { stdio: "inherit" });

execFileSync("sips", ["-Z", "1200", png], { stdio: "ignore" });
execFileSync("sips", ["-s", "format", "jpeg", "-s", "formatOptions", "86", png, "--out", jpg], { stdio: "ignore" });

const b64 = readFileSync(jpg).toString("base64");
writeFileSync(
  out,
  `/**
 * The trycommons.app share card, served at /og.jpg (http.ts). Generated by
 * scripts/og/render.mjs from scripts/og/card.html; do not edit by hand.
 */
const OG_JPEG_BASE64 =
  "${b64}";

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
let cached: Uint8Array<ArrayBuffer> | null = null;

/** The card's bytes, decoded once per isolate (no atob dependency). */
export function ogImageBytes(): Uint8Array<ArrayBuffer> {
  if (cached) return cached;
  const s = OG_JPEG_BASE64;
  const lookup = new Uint8Array(128);
  for (let i = 0; i < ALPHABET.length; i += 1) lookup[ALPHABET.charCodeAt(i)] = i;
  const pad = s.endsWith("==") ? 2 : s.endsWith("=") ? 1 : 0;
  const bytes = new Uint8Array(new ArrayBuffer((s.length / 4) * 3 - pad));
  let o = 0;
  for (let i = 0; i < s.length; i += 4) {
    const n =
      (lookup[s.charCodeAt(i)] << 18) |
      (lookup[s.charCodeAt(i + 1)] << 12) |
      (lookup[s.charCodeAt(i + 2)] << 6) |
      lookup[s.charCodeAt(i + 3)];
    if (o < bytes.length) bytes[o++] = (n >> 16) & 255;
    if (o < bytes.length) bytes[o++] = (n >> 8) & 255;
    if (o < bytes.length) bytes[o++] = n & 255;
  }
  cached = bytes;
  return bytes;
}
`
);
console.log(`share card: ${Math.round(statSync(jpg).size / 1024)} KB -> ${path.relative(root, out)}`);
console.log(`preview: ${jpg}`);
